version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    tty: true
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: password
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
